default_config:
logger:
  default: info

lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/ha-simple-slider-thermostat.js
      type: module

input_number:
  temp:
    icon: mdi:thermometer
    min: 18
    max: 35

input_boolean:
  heater:
    icon: mdi:fire

climate:
- platform: generic_thermostat
  name: Fake Thermostat
  heater: input_boolean.heater
  target_sensor: input_number.temp